## 6-е домашнее задание - Библиотека numpy

<b>Срок до 2 июня 2022г. (включительно)</b>

Подпишите этот блокнот: укажите ФИО и номер группы. Выполненное задание загрузите в свой репозиторий «<b>Spring_Python_2022</b>» в github в папку "<b>homework-6</b>".  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [1]:
import numpy  as np
from numpy.linalg import inv, det, matrix_rank , eig

In [5]:
np.linspace(-1.3,2.5,64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [6]:
def cyclic(N):
    x = np.array([1.0,2.0,3.0]) # The main sequence
    y = np.resize(x, 3*N)
    return y

In [7]:
cyclic(6)

array([1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2.,
       3.])

In [8]:
cyclic(9)

array([1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2., 3., 1., 2.,
       3., 1., 2., 3., 1., 2., 3., 1., 2., 3.])

In [9]:
cyclic(1)

array([1., 2., 3.])

3.	Создайте массив первых 10 нечетных целых чисел.

In [10]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [11]:
x = np.zeros((10,10))
x[0,:] = 1
x[:,0] = 1
x[9,:] = 1
x[:,9] = 1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [12]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [13]:
def f(n):
    return np.fromfunction(lambda i, j: i + j, (n, n), dtype=int) 

f(9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [14]:
f(6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5,  6],
       [ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10]])

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [15]:
np.vdot([1,1,1],[2,5,6])

13

In [16]:
np.dot(np.arange(9).reshape(3,3),np.array([[1],[2],[3]]))

array([[ 8],
       [26],
       [44]])

8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [17]:
x = np.linspace(0,1,20)
y_1 = np.cos(x)
y_2 = np.sin(x)

In [18]:
np.concatenate((y_1,y_2))

array([1.        , 0.99861528, 0.99446495, 0.9875605 , 0.97792106,
       0.96557333, 0.95055149, 0.93289715, 0.91265921, 0.88989371,
       0.8646637 , 0.83703905, 0.80709627, 0.77491828, 0.7405942 ,
       0.70421909, 0.66589368, 0.62572411, 0.58382164, 0.54030231,
       0.        , 0.05260728, 0.10506887, 0.15723948, 0.20897462,
       0.26013102, 0.310567  , 0.36014289, 0.40872137, 0.45616793,
       0.50235115, 0.54714315, 0.59041986, 0.63206143, 0.67195255,
       0.70998273, 0.74604665, 0.78004444, 0.81188195, 0.84147098])

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [19]:
-1 + 4*np.random.rand(3,5)

array([[ 0.87088227,  2.6419371 , -0.65843759,  0.80125328,  1.16471022],
       [-0.19918791,  2.64703296,  1.88171548,  2.28477913,  2.30475993],
       [ 0.19319454,  0.13227552,  1.52464322,  2.23054308,  0.31271451]])

10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [17]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.sum(A)

36

In [19]:
np.sum(A, axis=0)

array([ 9, 12, 15])

In [20]:
np.sum(A,axis=1)

array([ 3, 12, 21])

In [21]:
np.mean(A, axis=0)

array([3., 4., 5.])

In [22]:
np.mean(A, axis=1)

array([1., 4., 7.])

In [23]:
np.var(A, axis = 0)

array([6., 6., 6.])

In [24]:
np.var(A, axis = 1)

array([0.66666667, 0.66666667, 0.66666667])

In [25]:
np.std(A, axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [26]:
np.std(A, axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [27]:
B = np.arange(36).reshape(6,6)
B

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [28]:
(B-np.mean(B,axis=1))/np.std(B , axis=1)

array([[ -1.46385011,  -4.39155033,  -7.31925055, -10.24695077,
        -13.17465098, -16.1023512 ],
       [  2.04939015,  -0.87831007,  -3.80601028,  -6.7337105 ,
         -9.66141072, -12.58911094],
       [  5.56263042,   2.6349302 ,  -0.29277002,  -3.22047024,
         -6.14817046,  -9.07587068],
       [  9.07587068,   6.14817046,   3.22047024,   0.29277002,
         -2.6349302 ,  -5.56263042],
       [ 12.58911094,   9.66141072,   6.7337105 ,   3.80601028,
          0.87831007,  -2.04939015],
       [ 16.1023512 ,  13.17465098,  10.24695077,   7.31925055,
          4.39155033,   1.46385011]])

12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [29]:
A = np.array([[1,2,3,6],[2,1,2,9],[1,2,19,8],[5,9,11,2]])
A

array([[ 1,  2,  3,  6],
       [ 2,  1,  2,  9],
       [ 1,  2, 19,  8],
       [ 5,  9, 11,  2]])

In [30]:
s = np.argsort(A[:,2], axis = 0)
s

array([1, 0, 3, 2], dtype=int64)

In [31]:
A[s.argsort()]

array([[ 2,  1,  2,  9],
       [ 1,  2,  3,  6],
       [ 5,  9, 11,  2],
       [ 1,  2, 19,  8]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [32]:
A = np.arange(1,10).reshape(3,3)
B = np.dot(inv(A), A)
C = np.dot(A, inv(A))

In [33]:
B,C # Они разние по значении но однокого размера

(array([[ 12. ,  16. ,  12. ],
        [-10. , -16. ,  -6. ],
        [  1.5,   4. ,   2.5]]), array([[ 0. ,  1. , -0.5],
        [ 0. ,  2. , -1. ],
        [ 0. ,  3. ,  2.5]]))

14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [34]:
np.trace(B),np.trace(C)

(-1.5, 4.5)

15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [35]:
det(A),det(B),det(C)

(-9.51619735392994e-16, -127.99999999999997, 0.0)

In [36]:
matrix_rank(A),matrix_rank(B),matrix_rank(C)

(2, 3, 2)

In [37]:
w,v =eig(B)
w

array([-8.  +0.j        ,  3.25+2.33184476j,  3.25-2.33184476j])

In [38]:
w1,v1 =eig(C)
w1

array([0.  +0.j        , 2.25+1.71391365j, 2.25-1.71391365j])

16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [20]:
def pyamougolinika(f):
    h = 0.1
    sum_ = [0]
    diff= np.inf 
    while diff > 1e-4:
        x = np.linspace(3,4,int(1/h))
        y = f(x[:-1])*h
        sum_.append(np.sum(y))
        diff = abs(sum_[-1] - sum_[-2]) 
        h /= 10
    return sum_[-1]
    

In [21]:
f = lambda x: (x**2 + 3)/(x-2)

In [22]:
pyamougolinika(f)

10.352028318513577

In [23]:
def trapets(f):
    h = 0.1
    sum_ = [0]
    diff= np.inf 
    while diff > 1e-4:
        x = np.linspace(3,4,int(1/h))
        y = (f(x[0]) + 2*np.sum(f(x[1:-1])) + f(x[-1]))*(h/2)
        sum_.append(y)
        diff = abs(sum_[-1] - sum_[-2]) 
        h /= 10
    return sum_[-1]
    

In [24]:
trapets(f)

10.352028193513569

In [25]:
def simpysona(f):
    h = 0.1
    sum_ = [0]
    diff= np.inf 
    while diff > 1e-4:
        x = np.linspace(3,4,int(1/h))
        y = (f(x[0]) + 2*np.sum(f(x[2:-2:2])) + 4*np.sum(f(x[1::2])) + f(x[-1]))*(h/3)
        sum_.append(y)
        diff = abs(sum_[-1] - sum_[-2]) 
        h /= 10
    return sum_[-1]
    

In [26]:
simpysona(f)

10.352028193513563

In [27]:
#точное решение = 5.5 + 7ln(2)
5.5 + 7*np.log(2)

10.352030263919616